### ISSUE TITLE
Sign in with linkedin option is not coming in linkedin products

### ISSUE THREAD

**Issue by GouthamiSivakoti** [alexmarinmendez/linkedin-signin-with-openid#1]
Trying to implement signin with linkedin in identity server application.

When creating an app in linkedin developer account signin with linked option is not coming ,  and default scopes r_emailaddress and r_liteprofile are not coming. Before 2023 sep it was working fine. 

Please assist me .

**Comment by alexmarinmendez** [comment]
When you are in your Linkedin app page, go to Products section and Request access to the new "Sign In with Linkedin using OpenID Connect" (the one I show you in this screenshot)
![Captura de pantalla 2024-04-05 032052](https://github.com/alexmarinmendez/linkedin-signin-with-openid/assets/77815088/6f506991-570d-4e5c-b933-6787667bf74c)

The old method (Sign In with Linkedin) is deprecated from Linkedin. It doesn't work any more.
![Captura de pantalla 2024-04-05 032250](https://github.com/alexmarinmendez/linkedin-signin-with-openid/assets/77815088/d6ad8f88-c36d-4e76-935d-81b4c74c69e4)

Please write me if it was helpful or not.
